---
# Default values for FADI.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
spark:
  enabled: false
  Master:
    Name: spark-master
  WebUi:
    Name: spark-webui
  Worker:
    Name: spark-worker
  Zeppelin:
    Name: spark-zeppelin

superset:
  enabled: false

postgresql:
  enabled: false

minio:
  enabled: false

grafana:
  enabled: false

jupyterhub:
  enabled: false
  proxy:
    secretToken: 'af83775ec3bfaf0507ce596df51d491e7ed54450adc454038fa7405495465f19'

nifi:
  enabled: false

pgadmin:
  enabled: false

pulsar:
  enabled: true