# See the default values:https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/jupyterhub/values.yaml

# update secret Token
# disable prePuller (prePuller / hook / enabled: false)
# singleuser to type storage: none (not persistant)
# sqlite-memory for testing! (hub: db: type)

# in your config.yaml somewhere, you can disable the hook pre-puller
#prePuller:
#  hook:
#    enabled: false
#singleuser:
#  storage:
#    type: none
#hub:
#  db:
#    type: sqlite-memory

hub:
  db:
    type: sqlite-memory

rbac:
  enabled: true

proxy:
  secretToken: 'af83775ec3bfaf0507ce596df51d491e7ed54450adc454038fa7405495465f19'

#singleuser:
#  storage:
#    type: none
singleuser:
  storage:
      type: none
  # Defines the default image
  image:
    name: jupyter/minimal-notebook
    tag: 7d427e7a4dde
  profileList:
    - display_name: "Minimal environment"
      description: "To avoid too much bells and whistles: Python."
      default: true
    - display_name: "Datascience environment"
      description: "If you want the additional bells and whistles: Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook:7d427e7a4dde
    - display_name: "Spark environment"
      description: "The Jupyter Stacks spark image"
      kubespawner_override:
        image: jupyter/all-spark-notebook:latest

auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
      - admin
  dummy:
    password: 'password'
  ldap:
    dn:
      search: {}
      user: {}
    user: {}
  state:
    enabled: false
    cryptoKey:

prePuller:
  hook:
    enabled: false
